CREATE TABLE tb_core_permission(
	cod_record BIGINT PRIMARY KEY  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
	val_type INT NOT NULL,
	nam_application VARCHAR(100) NOT NULL,
	nam_module VARCHAR(100) NOT NULL,
	val_role VARCHAR(100) NOT NULL,
	val_key VARCHAR(100) NOT NULL,
	des_permission VARCHAR(250) NOT NULL,
	val_predecessor_permission VARCHAR(100) NULL,
	val_component VARCHAR(100) NULL,
	val_router VARCHAR(100) NULL,
	val_label  VARCHAR(100) NULL,
	val_root VARCHAR(100) NULL,
	val_icon VARCHAR(100) NULL,
	ind_toolbar BOOLEAN NULL,
	ind_root_toolbar BOOLEAN NULL,
	val_sequence INT NULL,
	sts_record BOOLEAN NOT NULL
);