CREATE TABLE tb_core_language(
	cod_record  BIGINT PRIMARY KEY  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
	val_key VARCHAR(100) NOT NULL,
	val_portugues VARCHAR(900) NULL,
	val_english VARCHAR(900) NULL,
	val_spanish VARCHAR(900) NULL,
	val_description VARCHAR(200) NULL,
	dtt_record TIMESTAMP(6) NOT NULL,
	dtt_update TIMESTAMP(6) NULL,
	sts_record BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX idx_unique_tb_core_language ON tb_core_language (val_key)