CREATE TABLE tb_core_business_unit_parameter (
	cod_record  BIGINT PRIMARY KEY  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
	val_key VARCHAR(100) NOT NULL,
	des_parameter VARCHAR(500),
	val_parameter VARCHAR(250) NOT NULL,
	sts_record BOOLEAN NOT NULL,
	cod_business_unit_fk BIGINT NOT NULL,
	CONSTRAINT "fk_tbCoreBusinessUnitParameter_tbCoreBusinessUnit" FOREIGN KEY (cod_business_unit_fk) REFERENCES tb_core_business_unit(cod_record)	
);